config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'

  namespace :admin do
    get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/edit'
    get 'users/create'
    get 'users/update'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comment/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :categories, :posts, :comments
  resources "contacts", only: [:new, :create ]

  namespace :admin do
    resources :categories, :posts, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# this is a class  ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# this is a class  Category
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where('name like ?', "%#{query}%")
  end
end

app/models/comment.rb
# frozen_string_literal: true

# this is a class  Comment
class Comment < ApplicationRecord
  belongs_to :posts
end

app/models/post.rb
# frozen_string_literal: true

# this is a class  Post
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  has_attached_file :image, :default_url => ":style/rails1.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/

  def self.search(query)
    where('title like ? or body like ?', "%#{query}%", "%#{query}%")
  end
end

app/models/user.rb
# frozen_string_literal: true

# class model user
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
   user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where('name like ? or body email ?', "%#{query}%", "%#{query}%")
  end

end

app/controllers/about_controller.rb
# frozen_string_literal: true

# this is a about controller
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# this is a Application controller
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# class Categories Controller
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# class comments controller
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment Added'
    redirect_to post_path(@post)
  end

private

  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

# class Contacts Controller
class ContactsController < ApplicationController
  def new; end

  def create; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# class Posts Controller
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

# this is a module AboutHelper
module AboutHelper
end

app/helpers/admin/comments_helper.rb
# frozen_string_literal: true

# this is a module Comments
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
# frozen_string_literal: true

# this is a module Posts
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

# this is a module Users
module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# this is a module ApplicationHelpe
module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# this is a module CategoriesHelper
module CategoriesHelper
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

# this is a module CommentHelper
module CommentHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

# this is a module ContactsHelper
module ContactsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# this is a module PostsHelper
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
           data-target=".navbar-collapse" >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><h1>rBlog<span>/Manager</span></h1></a>
        </div>
        <div id="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to "Posts", admin_posts_path %></li>
            <li class="<%= params[:controller] == 'admin/categories' ? 'active' : ''%>"><%= link_to "Categories", admin_categories_path %></li>
            <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to "Users", admin_users_path %></li>
          </ul>
          <%= render 'partials/admin/search' %>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <section>
      <div Class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="well">
              <div id="user nav" class="pull-right">
                <% if current_user %>
                  Logged in as <%= current_user.email %>.
                  <%= link_to "Log out", admin_logout_path %>
                <% else %>
                  <%= link_to "log in", admin_login_path%>
                <% end %>
                  </div>
              <div class="clearfix"></div>
              <!-- Alert & Messsages-->
              <% if flash[:notice] %>
                <div class="alert alert-success"><%= flash[:notice] %></div>
              <% end %>

              <% if flash[:alert] %>
                <div class="alert alert-danger"><%= flash[:alert]%></div>
              <% end %>
            <%= yield %>
            <div>
          </div>

        </div>
      </div>
    </section>

    <footer>
      <p>Copyright &copy: 2018, rBlog | <%= link_to "Frontend", root_path,target:'_blank' %></p>
    </footer>
  </body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login | RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'admin/login', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/partials/_comments.html.erb
<div class="comments">
 <h2 class="page-header"><%= @post.comments.length %>Comments</h2>
 <% @post.comments.each do |comment| %>
  <div class="comment">
   <div class="row">
    <div class="col-md-2">
     <%= image_tag("user.jpg") %>
    </div>
    <div class="col-md-10">
     <div class="well">
      <h4><%= comment.name %><span>/<%= comment.created_at.to_time
      .strftime('%B %e at %l:%M %p')%></span></h4>
      <%= comment.body %>
     </div>
    </div>
   </div>
  </div>
  <% end %>
 <div class="well add-comment">
  <h2 class="page-header">Add Comment</h2>
  <%= form_for([@post, @post.comments.build]) do |f|%>
    <div class="form-group">
     <%= f.label :name %><br />
     <%= f.text_field :name, class:'form-control'%><br />
    </div>
    <div class="form-group">
     <%= f.label :email %><br />
     <%= f.text_field :email, class:'form-control'%><br />
    </div>
    <div class="form-group">
     <%= f.label :body %><br />
     <%= f.text_area :body, class:'form-control'%><br />
    </div>
    <div class="form-group">
     <%= f.submit "Submit", class: 'btn btn-primary'%>
    </div>
  <% end %>
 </div>
</div>

app/views/partials/_footer.html.erb
<footer>
  <p>Copyright &copy; 2018, rBlog | <a href="login.html">Admin Login</a></a></p>
</footer>

app/views/partials/_search.html.erb
 <%= form_tag(posts_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:'form-control'%>
  </div>
  <%= submit_tag "Search", :name => nil, class:'btn btn-primary'%>
<% end%>

app/views/partials/_sidebar.html.erb
 <% if params[:controller] == 'posts' || params[:controller]== 'categories' %>
  <div class="list-group">
    <% @categories.each do |category|%>
     <%= link_to category.name, category_path(category.id), class:'list-group-item'%>
    <% end %>
  </div>
<% end %>

app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
<%= form_tag(admin_posts_path, :method => "get", id: "search-form",
class:"search-form pull-right") do %>
  <div class="form-group">
  <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:
   'form-control' %>
  </div>
  <%= submit_tag "search", :name => nil, class:'btn btn-primary' %>
<% end %>
<% elsif  params[:controller] == 'admin/categories' %>
  <%= form_tag(admin_categories_path, :method => "get", id: "search-form",
  class:"search-form pull-right") do %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class:
     'form-control' %>
    </div>
    <%= submit_tag "search", :name => nil, class:'btn btn-primary' %>
  <% end %>
<% elsif params[:controller] == 'admin/users' %>
  <%= form_tag(admin_users_path, :method => "get", id: "search-form",
  class:"search-form pull-right") do %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "Search Users", class:
     'form-control' %>
    </div>
    <%= submit_tag "search", :name => nil, class:'btn btn-primary' %>
  <% end %>
<% end %>