config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'

  namespace :admin do
    get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/edit'
    get 'users/create'
    get 'users/update'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comment/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :categories, :posts, :comments
  resources "contacts", only: [:new, :create ]

  namespace :admin do
    resources :categories, :posts, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

# this is a class  Category
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where('name like ?', "%#{query}%")
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

# this is a categories controller
class Admin::CategoriesController < Admin::ApplicationController
  before_action :verify_logged_in

  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category Updated'

      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    flash[:notice] = 'Category Removed'

      redirect_to admin_categories_path
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @categories = Category.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def show; end


private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# class Categories Controller
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

# this is a module categories
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# this is a module CategoriesHelper
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2> Edit Category</h2>
<%= form_for [:admin, @category] do |f|%>
    <!--check for errors-->
    <%if @category.errors.any?%>
      <% @category.errors.full_messages.each do |msg| %>
        <!--show errors-->
        <div class="alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control' %>
    </div>
    <br>
   <%= f.submit "submit", class:'btn btn-primary'%>
   <%=link_to 'Cancel', admin_categories_path, class:'btn btn-default'%>

<% end %>

app/views/admin/categories/index.html.erb
<h2 class="page-header">Manage Categories <%= link_to "Create New", new_admin_category_path,
class: 'btn btn-success pull-right'%></h2>
<table class="table table-striped">
  <tr>
    <th>Category Title</th>
    <th>Create Date</th>
    <th>Actions</th>
  </tr>
  <% @categories.each do |category| %>
  <tr>
    <td><% category.name %></td>
    <td><%= category.created_at.to_time.strftime('%B %e at %l:%M %p')%>
    <td><%= link_to "Edit",edit_admin_category_path(category), class:'btn
    btn-primary' %><%= link_to "Delete", admin_category_path(category), class:
    'btn btn-danger', method: :delete, date: {confirm: 'Are you sure'}%></td>
  </tr>
  <% end %>
  </table>
  <%= will_paginate @posts %>

app/views/admin/categories/new.html.erb
<h2> Add New Category</h2>
<%= form_for [:admin, @category] do |f|%>
    <!--check for errors-->
    <%if @category.errors.any?%>
      <% @category.errors.full_messages.each do |msg| %>
        <!--show errors-->
        <div class="alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control' %>
    </div>
    <br>
   <%= f.submit "submit", class:'btn btn-primary'%>
   <%=link_to 'Cancel', admin_categories_path, class:'btn btn-default'%>

<% end %>