config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'

  namespace :admin do
    get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/index'
    get 'users/show'
    get 'users/new'
    get 'users/edit'
    get 'users/create'
    get 'users/update'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comment/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :categories, :posts, :comments
  resources "contacts", only: [:new, :create ]

  namespace :admin do
    resources :categories, :posts, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# this is a class  ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# this is a class  Category
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where('name like ?', "%#{query}%")
  end
end

app/models/comment.rb
# frozen_string_literal: true

# this is a class  Comment
class Comment < ApplicationRecord
  belongs_to :posts
end

app/models/post.rb
# frozen_string_literal: true

# this is a class  Post
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :category_id, presence: true
  validates :body, presence: true

  has_attached_file :image, :default_url => ":style/rails1.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\z/

  def self.search(query)
    where('title like ? or body like ?', "%#{query}%", "%#{query}%")
  end
end

app/models/user.rb
# frozen_string_literal: true

# class model user
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
   user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where('name like ? or body email ?', "%#{query}%", "%#{query}%")
  end

end

app/controllers/about_controller.rb
# frozen_string_literal: true

# this is a about controller
class AboutController < ApplicationController
  def index; end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# this is a users controller
class Admin::UsersController < Admin::ApplicationController
  before_action :verify_logged_in

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def new
    @page_title = 'Add User'
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User Created'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User Updated'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User Removed'
    redirect_to admin_users_path
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# this is a Application controller
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# class Categories Controller
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# class comments controller
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment Added'
    redirect_to post_path(@post)
  end

private

  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

# class Contacts Controller
class ContactsController < ApplicationController
  def new; end

  def create; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# class Posts Controller
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

# this is a module AboutHelper
module AboutHelper
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

# this is a module categories
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
# frozen_string_literal: true

# this is a module Comments
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
# frozen_string_literal: true

# this is a module Posts
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
# frozen_string_literal: true

# this is a module Sessions
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

# this is a module Users
module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# this is a module ApplicationHelpe
module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# this is a module CategoriesHelper
module CategoriesHelper
end

app/helpers/comment_helper.rb
# frozen_string_literal: true

# this is a module CommentHelper
module CommentHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

# this is a module ContactsHelper
module ContactsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# this is a module PostsHelper
module PostsHelper
end

app/views/admin/users/edit.html.erb
<h2> Edit User</h2>
<%= form_for [:admin, @user] do |f|%>
    <!--check for errors-->
    <%if @user.errors.any?%>
      <% @user.errors.full_messages.each do |msg| %>
        <!--show errors-->
        <div class="alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
       <%= f.label :email %>
       <%= f.select :email,  class: 'form-control'%>
    </div>

    <div class="form-group">
       <%= f.label :new_password %>
       <%= f.password_field :new_password, class: 'from-control'%>
    </div>

    <div class="form-group">
       <%= f.label :new_password_confirmation %>
       <%= f.password_field :new_password_confirmation, class: 'from-control'%>
    </div>
    <br>
   <%= f.submit "submit", class:'btn btn-primary'%>
   <%=link_to 'Cancel', admin_users_path, class:'btn btn-default'%>

<% end %>

app/views/admin/users/index.html.erb
<h2 class="page-header"> Manage Users <%= link_to "Create New", new_admin_user_path,
class:'btn btn-success pull-right'%></h2>
<% if @users.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>
      <% @users.each do |user| %>
      <tr>
        <td><% user.name %></td>
        <td><% user.email %></td>
        <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p')%></td>
        <td><%= link_to "Edit",edit_admin_user_path(user), class:'btn
        btn-primary' %><%= link_to "Delete", admin_user_path(user), class:
        'btn btn-danger', method: :delete, date: {confirm: 'Are you sure'}%></td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @users %>
<% else %>
   <p>There are no posts</p>
<% end %>

app/views/admin/users/new.html.erb
<h2> Add New User</h2>
<%= form_for [:admin, @user] do |f|%>
    <!--check for errors-->
    <%if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
        <!--show errors-->
        <div class="alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group">
       <%= f.label :name %><br />
       <%= f.text_field :name, class: 'form-control' %> <br />
    </div>

    <div class="form-group">
       <%= f.label :email %><br />
       <%= f.text_field :email,  class: 'form-control'%><br />
    </div>

    <div class="form-group">
       <%= f.label :password %><br />
       <%= f.password_field :password, class: 'from-control'%><br />
    </div>

    <div class="form-group">
       <%= f.label :password_confirmation %><br />
       <%= f.password_field :password_confirmation, class: 'from-control'%><br />
    </div>

   <%= f.submit "submit", class:'btn btn-primary'%>
   <%=link_to 'Cancel', admin_users_path, class:'btn btn-default'%>

<% end %>